name: C Library CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'c/**'
      - '.github/workflows/c.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'c/**'

jobs:
  test:
    name: Build and Test C Library
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: gcc
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build
      
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake ninja
      
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake ninja
      
      - name: Configure CMake
        run: |
          cd c
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON
        env:
          CC: ${{ matrix.compiler }}
      
      - name: Build
        run: |
          cd c/build
          cmake --build .
      
      - name: Test
        run: |
          cd c/build
          ctest --output-on-failure
      
      - name: Install
        if: runner.os != 'Windows'
        run: |
          cd c/build
          sudo cmake --install .

